import os
# print(dir(os))
# print(os.getcwd())
# os.chdir("C://")
# print(os.getcwd())
# f=open("sid.txt")
# print(os.listdir())
# print(os.listdir("C://"))
# print(type(os.listdir("C://")))
# os.mkdir("this")
# os.makedirs("this/that")
# os.rename("sid.txt","codewithsid.txt")
# print(os.environ.get('Path'))
# print(os.path.join("C:/","/harry.txt"))
# print(os.path.exists("C://Program Files"))
# print(os.path.isfile("C://Program Files"))
print(os.path.isdir("C://Program Files"))